# Generated by Django 6.0.2 on 2026-09-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('predicted_class', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('glioma_probability', models.FloatField()),
                ('meningioma_probability', models.FloatField()),
                ('no_tumor_probability', models.FloatField()),
                ('pituitary_tumor_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
